meshhq/club-hub-core

dist/models/shared.d.ts, dist/models/shared.js, src/models/shared.ts
Updating PublicationStatus to include more options
=> john-daly/ch1881/update-publicationstatus-to-include-message

dist/index.d.ts, dist/models/section.d.ts, dist/models/section.js, dist/models/shared.d.ts, src/index.ts, src/models/section.ts, src/models/shared.ts
- Adding Section and Page interfaces to the project
- Adding a Timestamps interface
=> john-daly/ch1931/add-section-interface-to-core

src/service/section.ts, src/service/user.ts
Added Service File for Section CRUD
=> John daly/ch1928/crud api for sections

dist/models/message.d.ts, src/models/message.ts
- I refactored the messaging logic I put in last week which allowed me to remove a lot of the message type interfaces I created. This PR is just removing unused interfaces.
=> Updated the message types

src/models/club.ts
Added optional interface for club settings.
Also, added the missing ClubInfo Interfaces
=> Added Club Info and Settings interfaces

dist/models/calendar.d.ts, dist/models/club.d.ts, dist/models/club.js
Forgot to build this before last merge...
=> build-json-rules-engine-fixes

dist/models/club.d.ts, src/models/club.ts
This PR adds a `phoneNumber` property to clubs.
=> Adding phone number to club

dist/models/calendar.d.ts, dist/models/shared.d.ts, dist/models/shared.js, src/models/calendar.ts, src/models/shared.ts
Adding an HoursOfOperation type for the ReservationSettings
=> john-daly/ch2228/add-hoursofoperation-type-to-core-for-reservationsetting

dist/models/calendar.d.ts, dist/models/shared.d.ts, dist/models/shared.js, src/models/calendar.ts, src/models/shared.ts
Adding types for the privileges field on ReservationSetting
=> john-daly/ch2230/add-privilege-type-to-reservationsetting

dist/models/calendar.d.ts, dist/models/calendar.js, dist/models/club.d.ts, dist/models/shared.d.ts, dist/models/shared.js, dist/models/user.d.ts, src/models/calendar.ts, src/models/club.ts, src/models/shared.ts, src/models/user.ts
* Renamed calendar associated resources. 
* Added calendar group types and names. 
* Added `template` type to publication status
* Updated display settings properties.
=> Cleaning up types

dist/index.d.ts, dist/index.js, dist/models/event.d.ts, dist/models/order.d.ts, src/index.ts, src/models/event.ts, src/models/order.ts
Changed import (was not working for me on mobile)
Change `String` typing to `string`
Added `_id` to Order Model
=> Updated Core

dist/models/club.d.ts, dist/models/event.d.ts, src/models/club.ts, src/models/event.ts
* Adds website config to core. 
* Adds maxGuests property to event.
=> Adding website config

dist/models/club.d.ts, src/models/club.ts, src/models/shared.ts
Adds tzid, lat and lon to club object.
=> Updating core

dist/models/user.d.ts, dist/models/user.js, src/models/user.ts
- Added host IDs to the user model.
- Added type GUEST to member status enum
=> Added hostIds and guest as member status

dist/models/calendar.d.ts, dist/models/calendar.js, src/models/calendar.ts
- Added type 'GOLF' to calendar groups.
- Added type 'TENNIS' to calendar group.s
- Added name 'Tee Times' to calendar group names.
=> Added a golf calendar group

dist/models/event.d.ts, dist/models/message.d.ts, dist/models/post.d.ts, src/models/event.ts, src/models/message.ts, src/models/post.ts
- Removed the field description from posts and events.
- Removed the filed text from message.
=> Removed unused content descriptions from resources

dist/models/action.d.ts, dist/models/action.js, dist/models/calendar.d.ts, dist/models/calendar.js, src/models/action.ts, src/models/calendar.ts
Updates to 
1. Action Types
2. Calendar Group Types
=> Updating types

dist/models/event.d.ts, dist/models/event.js, src/models/event.ts
- Adding ‘blockCalendar’ to Event model
- Adding ‘Blocked’ to ‘AvailableEventStatus’ enum
=> john-daly/ch2560/update-event-model-on-core

dist/models/event.d.ts, dist/service/event.js, src/models/event.ts, src/service/event.ts
Changing ‘rsvp’ field on Participant to be ‘checkedIn’
=> john-daly/ch2648/update-rsvp-on-participant-to-be-checkedin

dist/models/club.d.ts, src/models/club.ts
Adding placeholder image to the club.website model
=> Adding placeholder image to club.website

dist/models/user.d.ts, src/models/user.ts
Updating the User model to have an `addresses` field, which is an array of Location’s
=> john-daly/ch2886/make-user-address-an-array-of-locations-core

dist/models/user.d.ts, src/models/user.ts
Removing City, State, Location, and ZIP from User model
=> john-daly/ch2940/remove-city-state-location-and-zip-from-user

dist/index.d.ts, dist/models/club.d.ts, src/index.ts, src/models/club.ts
Added domain to UnprotectedClubModel and exported Response interfaces.
=> Added Domain

dist/models/calendar.d.ts, dist/models/club.d.ts, src/models/calendar.ts, src/models/club.ts
Removed Duplicate interface for AvailableEvent.
=> Available Event Duplicate

dist/models/club.d.ts, dist/models/relation.d.ts, dist/models/relation.js, dist/models/user.d.ts, src/models/club.ts, src/models/relation.ts, src/models/user.ts
- Adding types for Relation
- Making `shortName` optional in Club types
=> john-daly/ch2981/add-relation-model-to-core

dist/models/calendar.d.ts, dist/models/calendar.js, dist/models/event.d.ts, dist/models/note.d.ts, dist/models/note.js, dist/models/user.d.ts, src/models/calendar.ts, src/models/event.ts, src/models/note.ts, src/models/user.ts
Tee Times -> Tee Time https://app.clubhouse.io/meshstudio/story/2934/change-tee-times-to-tee-time
Core support for this https://app.clubhouse.io/meshstudio/story/2899/add-add-to-feed-option-for-events
=> Adding user fields and a few other items

src/models/subModels/index.ts
=> Export shared model

dist/models/user.d.ts, src/models/user.ts
Adding member number model. This supports the whole member number suffix jazz that we need.
=> Adding member number

dist/models/restaurant.d.ts, src/models/restaurant.ts
- Updating Restaurant model types
=> john-daly/ch3025/update-restaurant-models-on-core

dist/models/restaurant.d.ts, dist/models/section.d.ts, src/models/restaurant.ts, src/models/section.ts
Adding orderingIndex to MenuSection, Section, and Page
=> john-daly/ch3050/add-orderindex-to-menusection-section-and

dist/models/club.d.ts, dist/models/club.js, src/models/club.ts
Updated mobile navigation interfaces.
=> Updated Mobile Config

dist/models/response.d.ts, src/models/response.ts
Added state response interfaces for admin and non-admin state routes.
=> Added State Response Interfaces

dist/models/message.d.ts, src/models/message.ts
Adding `eventIDs` to the Message model
=> john-daly/ch3151/add-eventids-to-message-model-on-core

dist/models/response.d.ts, src/models/response.ts
=> Updated Response Interfaces

dist/models/user.d.ts, src/models/user.ts
=> Adding the query filter model to group

src/models/subModels/shared/image.ts
- Added a field for original image and aspect ratio
=> added original and aspect

dist/models/subModels/shared/image.d.ts
=> recompiled

dist/models/subModels/shared/image.d.ts, src/models/subModels/shared/image.ts
- Made the aspect ration optional
=> Make Aspect Optional

dist/models/club.d.ts, src/models/club.ts
Adding _id to ClubSettings interface
=> john-daly/ch3313/add-id-to-clubsettings-interface-in-core

dist/models/notificationPreference.d.ts, dist/models/response.d.ts, src/models/notificationPreference.ts, src/models/response.ts
Added global setting to Notification Preference response and model.
=> Updated Preference Models

dist/models/club.d.ts, src/models/club.ts
Adds `orderIndex` and `_id` to quick link.
=> Updating quick link

dist/models/notification.d.ts, dist/models/notification.js, src/models/notification.ts
=> Updated status options

dist/models/event.d.ts, src/models/event.ts
Changing ‘image’ field to be ‘images’ on Event model
=> john-daly/ch3347/update-event-model-on-core-to-support-array

package.json, src/client/index.ts, src/util/logger.ts
=> Added logger

dist/constants.d.ts, dist/constants.js, src/constants.ts
=> Adding clubs

dist/models/subModels/shared/richContent.d.ts, src/models/subModels/shared/richContent.ts
- Adding a field to capture the published html of a message
=> added published html

dist/models/club.d.ts, src/models/club.ts
=> added heartbeat
